<?php

namespace ContainerR2AkFPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZrqmD3AService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZrqmD3A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZrqmD3A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rentRepository' => ['privates', 'App\\Repository\\RentRepository', 'getRentRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.ZrqmD3A.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.ZrqmD3A": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'rentRepository' => 'App\\Repository\\RentRepository',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
