<?php

namespace ContainerR2AkFPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Service_FilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'liip_imagine.service.filter' shared service.
     *
     * @return \Liip\ImagineBundle\Service\FilterService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['liip_imagine.service.filter'] = new \Liip\ImagineBundle\Service\FilterService(($container->services['liip_imagine.data.manager'] ?? $container->load('getLiipImagine_Data_ManagerService')), ($container->services['liip_imagine.filter.manager'] ?? $container->load('getLiipImagine_Filter_ManagerService')), ($container->services['liip_imagine.cache.manager'] ?? $container->load('getLiipImagine_Cache_ManagerService')), false, $container->parameters['liip_imagine.webp.options'], ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
