<?php

namespace ContainerR2AkFPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RentRepository' shared autowired service.
     *
     * @return \App\Repository\RentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RentRepository'] = new \App\Repository\RentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
