<?php

namespace ContainerR2AkFPA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenterControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RenterController' shared autowired service.
     *
     * @return \App\Controller\RenterController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RenterController'] = $instance = new \App\Controller\RenterController();

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\RenterController', $container));

        return $instance;
    }
}
