<?php

namespace ContainerZ42hTeB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RentController' shared autowired service.
     *
     * @return \App\Controller\RentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RentController.php';

        $container->services['App\\Controller\\RentController'] = $instance = new \App\Controller\RentController();

        $instance->setContainer(($container->privates['.service_locator.0QcI221'] ?? $container->load('get_ServiceLocator_0QcI221Service'))->withContext('App\\Controller\\RentController', $container));

        return $instance;
    }
}
