<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGqZTGxl\App_KernelDeDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGqZTGxl/App_KernelDeDebugContainer.php') {
    touch(__DIR__.'/ContainerGqZTGxl.legacy');

    return;
}

if (!\class_exists(App_KernelDeDebugContainer::class, false)) {
    \class_alias(\ContainerGqZTGxl\App_KernelDeDebugContainer::class, App_KernelDeDebugContainer::class, false);
}

return new \ContainerGqZTGxl\App_KernelDeDebugContainer([
    'container.build_hash' => 'GqZTGxl',
    'container.build_id' => '3513526d',
    'container.build_time' => 1656277239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGqZTGxl');
