<?php

namespace ContainerGqZTGxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarTypeFormTypeService extends App_KernelDeDebugContainer
{
    /**
     * Gets the private 'App\Form\CarTypeFormType' shared autowired service.
     *
     * @return \App\Form\CarTypeFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CarTypeFormType.php';

        return $container->privates['App\\Form\\CarTypeFormType'] = new \App\Form\CarTypeFormType();
    }
}
