<?php

namespace ContainerGqZTGxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarFormTypeService extends App_KernelDeDebugContainer
{
    /**
     * Gets the private 'App\Form\CarFormType' shared autowired service.
     *
     * @return \App\Form\CarFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CarFormType.php';

        return $container->privates['App\\Form\\CarFormType'] = new \App\Form\CarFormType();
    }
}
