<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rent extends \App\Entity\Rent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'isMonthlyRecurring', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'car', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'paidMonths', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'finished'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'isMonthlyRecurring', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'car', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'isPaid', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'paidMonths', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'duration', '' . "\0" . 'App\\Entity\\Rent' . "\0" . 'finished'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(\DateTimeInterface $startDate): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate(?\DateTimeInterface $endDate): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$endDate]);

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsMonthlyRecurring(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsMonthlyRecurring', []);

        return parent::getIsMonthlyRecurring();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsMonthlyRecurring(bool $isMonthlyRecurring): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsMonthlyRecurring', [$isMonthlyRecurring]);

        return parent::setIsMonthlyRecurring($isMonthlyRecurring);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(float $price): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCar(): ?\App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCar', []);

        return parent::getCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCar(?\App\Entity\Car $car): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCar', [$car]);

        return parent::setCar($car);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPaid(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPaid', []);

        return parent::getIsPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPaid(bool $isPaid): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPaid', [$isPaid]);

        return parent::setIsPaid($isPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidMonths(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidMonths', []);

        return parent::getPaidMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidMonths(?int $paidMonths): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidMonths', [$paidMonths]);

        return parent::setPaidMonths($paidMonths);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration(?int $duration): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinished(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinished', []);

        return parent::getFinished();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinished(?bool $finished): \App\Entity\Rent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinished', [$finished]);

        return parent::setFinished($finished);
    }

}
